#!/usr/bin/env bash
# ralph/lib/branch_management.sh — GitHub PR creation and per-story feature branch management
#
# Extracted from ralph.sh to reduce monolith size.
# Sourced by ralph.sh after JQ, PRD_FILE, log_ralph_event, SPIRAL_BASE_BRANCH are defined.
#
# Functions provided:
#   create_github_pr      — US-143: push + open GitHub PR for story
#   create_story_branch   — US-157: create/reuse per-story feature branch
#   finalize_story_branch — US-157: merge or push story branch after pass

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && echo "Source this file, do not execute it directly." && exit 1

# ── GitHub PR creation (US-143) ─────────────────────────────────────────────
create_github_pr() {
  local story_id="$1" story_title="$2" commit_sha="$3"
  local pr_base="${SPIRAL_PR_BASE_BRANCH:-main}"
  local pr_branch="spiral/${story_id}"
  local draft_flag=""
  [[ "${SPIRAL_PR_DRAFT:-false}" == "true" ]] && draft_flag="--draft"

  if ! command -v gh &>/dev/null; then
    echo "  [pr] SKIP: gh CLI not found. Install from https://cli.github.com to enable PR creation."
    return 0
  fi
  if ! gh auth status &>/dev/null 2>&1; then
    echo "  [pr] SKIP: gh CLI is not authenticated. Run 'gh auth login' to enable PR creation."
    return 0
  fi

  echo "  [pr] Pushing $commit_sha to branch $pr_branch..."
  if ! git push origin "${commit_sha}:refs/heads/${pr_branch}" --force 2>&1; then
    echo "  [pr] WARNING: git push failed -- skipping PR creation"
    return 0
  fi

  local story_desc
  story_desc=$($JQ -r --arg id "$story_id" \
    '.userStories[] | select(.id == $id) | .description // ""' "$PRD_FILE" 2>/dev/null || echo "")
  local ac_list
  ac_list=$($JQ -r --arg id "$story_id" \
    '.userStories[] | select(.id == $id) | .acceptanceCriteria // [] | .[] | "- [ ] \(.)"' \
    "$PRD_FILE" 2>/dev/null || echo "")

  local pr_body
  pr_body="## Story: ${story_id}

${story_desc}

## Acceptance Criteria

${ac_list}

---
*SPIRAL Run ID:* \`${SPIRAL_RUN_ID:-unknown}\`
*Commit:* \`${commit_sha}\`
*Generated by [SPIRAL](https://github.com/anthropics/spiral) autonomous dev loop*"

  gh label create "spiral-ai" --color "0075ca" --description "SPIRAL AI-generated story" 2>/dev/null || true

  local existing_pr_url
  existing_pr_url=$(gh pr list --head "$pr_branch" --json url --jq '.[0].url' 2>/dev/null || echo "")
  if [[ -n "$existing_pr_url" ]]; then
    echo "  [pr] PR already exists: $existing_pr_url"
    $JQ --arg id "$story_id" --arg url "$existing_pr_url" \
      '(.userStories[] | select(.id == $id)) |= . + {"_prUrl": $url}' \
      "$PRD_FILE" >"${PRD_FILE}.tmp" && mv "${PRD_FILE}.tmp" "$PRD_FILE" || true
    return 0
  fi

  local pr_url
  # shellcheck disable=SC2086
  pr_url=$(gh pr create \
    --base "$pr_base" --head "$pr_branch" --title "$story_title" \
    --body "$pr_body" --label "spiral-ai" $draft_flag 2>&1) || {
    echo "  [pr] WARNING: gh pr create failed: $pr_url"
    return 0
  }

  pr_url=$(echo "$pr_url" | grep -E '^https?://' | head -1 || echo "")
  if [[ -n "$pr_url" ]]; then
    echo "  [pr] Created PR: $pr_url"
    $JQ --arg id "$story_id" --arg url "$pr_url" \
      '(.userStories[] | select(.id == $id)) |= . + {"_prUrl": $url}' \
      "$PRD_FILE" >"${PRD_FILE}.tmp" && mv "${PRD_FILE}.tmp" "$PRD_FILE" || true
    log_ralph_event "pr_created" "\"storyId\":\"$story_id\",\"prUrl\":\"$pr_url\",\"branch\":\"$pr_branch\""
  else
    echo "  [pr] WARNING: PR created but URL not captured"
  fi
}

# ── Per-story feature branch management (US-157) ─────────────────────────────
create_story_branch() {
  local story_id="$1"
  STORY_BRANCH=""
  [[ -z "${SPIRAL_BRANCH_PREFIX:-}" ]] && return 0

  local branch_name="${SPIRAL_BRANCH_PREFIX}/${story_id}"
  local worktree_branches
  worktree_branches=$(git worktree list --porcelain 2>/dev/null |
    grep '^branch ' | sed 's|^branch refs/heads/||' || true)
  if echo "$worktree_branches" | grep -qx "$branch_name" 2>/dev/null; then
    echo "  [branch] WARNING: $branch_name already checked out in another worktree -- skipping"
    return 0
  fi

  echo "  [branch] Switching to story branch: $branch_name"
  if git checkout -B "$branch_name" 2>&1; then
    STORY_BRANCH="$branch_name"
    log_ralph_event "story_branch_created" "\"storyId\":\"$story_id\",\"branch\":\"$branch_name\""
    echo "  [branch] On branch: $branch_name"
    if type undo_log_record &>/dev/null; then
      local _prev_branch
      _prev_branch=$(git rev-parse --abbrev-ref HEAD@{1} 2>/dev/null || echo "${SPIRAL_BASE_BRANCH:-main}")
      undo_log_record "$story_id" "branch_create" "$branch_name" \
        "git checkout ${_prev_branch} 2>/dev/null || git checkout -; git branch -D $branch_name 2>/dev/null || true"
    fi
  else
    echo "  [branch] WARNING: failed to create/switch to $branch_name -- continuing on current branch"
    STORY_BRANCH=""
  fi
}

finalize_story_branch() {
  local story_id="$1"
  local _commit_sha="${2:-}"
  [[ -z "${SPIRAL_BRANCH_PREFIX:-}" || -z "$STORY_BRANCH" ]] && return 0

  local branch_name="$STORY_BRANCH"
  local base_branch="${SPIRAL_BASE_BRANCH:-main}"

  if [[ "${SPIRAL_CREATE_PRS:-false}" == "true" ]]; then
    if declare -f policy_check >/dev/null 2>&1 && ! policy_check "git_push" "M"; then
      echo "  [policy] BLOCKED: git_push denied by .spiral/policy.json -- branch kept locally"
      declare -f policy_log_violation >/dev/null 2>&1 &&
        policy_log_violation "$PRD_FILE" "$story_id" "git_push" "M" "${JQ:-jq}"
      log_ralph_event "policy_violation" \
        "\"story_id\":\"$story_id\",\"operation\":\"git_push\",\"phase\":\"M\"" 2>/dev/null || true
      return 0
    fi
    echo "  [branch] SPIRAL_CREATE_PRS=true -- pushing $branch_name to remote"
    if git push origin "$branch_name" 2>&1; then
      echo "  [branch] Pushed: $branch_name (open for PR)"
      log_ralph_event "story_branch_pushed" "\"storyId\":\"$story_id\",\"branch\":\"$branch_name\""
    else
      echo "  [branch] WARNING: failed to push $branch_name -- branch kept locally"
    fi
    return 0
  fi

  if declare -f policy_check >/dev/null 2>&1 && ! policy_check "git_merge" "M"; then
    echo "  [policy] BLOCKED: git_merge denied by .spiral/policy.json -- branch kept locally"
    declare -f policy_log_violation >/dev/null 2>&1 &&
      policy_log_violation "$PRD_FILE" "$story_id" "git_merge" "M" "${JQ:-jq}"
    log_ralph_event "policy_violation" \
      "\"story_id\":\"$story_id\",\"operation\":\"git_merge\",\"phase\":\"M\"" 2>/dev/null || true
    STORY_BRANCH=""
    return 0
  fi

  echo "  [branch] Merging $branch_name -> $base_branch (--no-ff)"
  if ! git checkout "$base_branch" 2>&1; then
    echo "  [branch] WARNING: failed to checkout $base_branch -- $branch_name kept"
    return 0
  fi

  local merge_msg="Merge story branch ${branch_name} into ${base_branch}

Story: ${story_id}"
  if git merge --no-ff "$branch_name" -m "$merge_msg" 2>&1; then
    echo "  [branch] Merged $branch_name into $base_branch"
    log_ralph_event "story_branch_merged" "\"storyId\":\"$story_id\",\"branch\":\"$branch_name\",\"base\":\"$base_branch\""
    if [[ "${SPIRAL_KEEP_STORY_BRANCHES:-false}" != "true" ]]; then
      git branch -d "$branch_name" 2>/dev/null || true
      echo "  [branch] Deleted: $branch_name"
    else
      echo "  [branch] Kept: $branch_name (SPIRAL_KEEP_STORY_BRANCHES=true)"
    fi
    type undo_log_cleanup &>/dev/null && undo_log_cleanup "$story_id"
  else
    echo "  [branch] WARNING: merge conflict -- manual resolution required"
    echo "  [branch] Aborting merge; $branch_name kept on $base_branch"
    git merge --abort 2>/dev/null || true
    log_ralph_event "story_branch_merge_conflict" "\"storyId\":\"$story_id\",\"branch\":\"$branch_name\",\"base\":\"$base_branch\""
  fi
  STORY_BRANCH=""
}
