"""Shared test fixtures and Hypothesis strategies for SPIRAL property tests."""
import os
import sys
import json
import pytest
from hypothesis import strategies as st, HealthCheck

# Ensure lib/ is importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "lib"))

# ── Common settings for suppressing slow-generation health checks ──────────
# The PRD strategy is inherently composite; suppress slow/large warnings.
HEALTH_SUPPRESSED = [HealthCheck.too_slow, HealthCheck.large_base_example]

# ── Hypothesis strategies ──────────────────────────────────────────────────

PRIORITIES = ["critical", "high", "medium", "low"]
COMPLEXITIES = ["small", "medium", "large"]

# Lightweight text strategies (avoid expensive full-unicode generation)
_title_st = st.from_regex(r"[A-Za-z][A-Za-z0-9 _-]{2,30}", fullmatch=True)
_desc_st = st.text(
    alphabet="abcdefghijklmnopqrstuvwxyz 0123456789.,",
    min_size=0, max_size=60,
)
_ac_item_st = st.from_regex(r"[A-Za-z][A-Za-z0-9 ]{2,40}", fullmatch=True)
_note_st = st.from_regex(r"[A-Za-z][A-Za-z0-9 ]{2,30}", fullmatch=True)
_file_st = st.from_regex(r"[a-z][a-z0-9_/]{1,20}\.(py|js|ts|sh)", fullmatch=True)


@st.composite
def valid_prd(draw, min_stories=1, max_stories=10):
    """Generate a valid prd.json dict with consistent forward-only dependencies.

    Uses sequential IDs (US-001, US-002, ...) to avoid collision loops.
    Dependencies only reference earlier IDs, guaranteeing a valid DAG.
    """
    n = draw(st.integers(min_value=min_stories, max_value=max_stories))

    stories = []
    for i in range(n):
        sid = f"US-{i + 1:03d}"
        earlier_ids = [f"US-{j + 1:03d}" for j in range(i)]

        # Pick deps from earlier IDs only (forward deps = no cycles)
        deps = []
        if earlier_ids:
            deps = draw(st.lists(
                st.sampled_from(earlier_ids),
                max_size=min(2, len(earlier_ids)),
                unique=True,
            ))

        story = {
            "id": sid,
            "title": draw(_title_st),
            "passes": draw(st.booleans()),
            "priority": draw(st.sampled_from(PRIORITIES)),
            "description": draw(_desc_st),
            "acceptanceCriteria": draw(st.lists(_ac_item_st, min_size=1, max_size=3)),
            "dependencies": deps,
        }

        # Optional fields (coin flip)
        if draw(st.booleans()):
            story["estimatedComplexity"] = draw(st.sampled_from(COMPLEXITIES))
        if draw(st.booleans()):
            story["technicalNotes"] = draw(st.lists(_note_st, max_size=2))
        if draw(st.booleans()):
            story["filesTouch"] = draw(st.lists(_file_st, max_size=3))

        stories.append(story)

    product = draw(st.from_regex(r"[A-Z][a-z]{2,10}", fullmatch=True))
    branch = draw(st.from_regex(r"[a-z]{2,10}", fullmatch=True))

    return {
        "productName": product,
        "branchName": branch,
        "userStories": stories,
    }


@st.composite
def invalid_prd_missing_field(draw):
    """Generate a PRD with one required field missing."""
    prd = draw(valid_prd(min_stories=1, max_stories=3))
    field = draw(st.sampled_from(["productName", "branchName", "userStories"]))
    del prd[field]
    return prd, field


@st.composite
def prd_with_duplicate_ids(draw):
    """Generate a PRD that has duplicate story IDs."""
    prd = draw(valid_prd(min_stories=2, max_stories=4))
    # Duplicate first story's ID onto last
    prd["userStories"][-1]["id"] = prd["userStories"][0]["id"]
    return prd


@st.composite
def prd_with_cycle(draw):
    """Generate a PRD that has a dependency cycle."""
    prd = draw(valid_prd(min_stories=3, max_stories=5))
    stories = prd["userStories"]
    # Create cycle: last depends on second-to-last, which depends on last
    stories[-1]["dependencies"] = [stories[-2]["id"]]
    stories[-2]["dependencies"] = [stories[-1]["id"]]
    return prd


@st.composite
def prd_with_dangling_dep(draw):
    """Generate a PRD with a dependency pointing to a non-existent ID."""
    prd = draw(valid_prd(min_stories=1, max_stories=3))
    # US-9999 will never be generated by our sequential strategy
    prd["userStories"][0]["dependencies"] = ["US-9999"]
    return prd


@pytest.fixture
def example_prd():
    """Load the example prd.json."""
    path = os.path.join(os.path.dirname(__file__), "..", "templates", "prd.example.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture
def tmp_prd(tmp_path):
    """Create a temp prd.json and return its path."""
    def _write(prd_dict):
        path = tmp_path / "prd.json"
        path.write_text(json.dumps(prd_dict, indent=2), encoding="utf-8")
        return str(path)
    return _write
