"""Property-based tests for check_dag.py cycle detection."""
import os
import sys
import pytest
from hypothesis import given, settings, assume
from conftest import valid_prd, prd_with_cycle

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "lib"))
from check_dag import find_cycles


class TestNoCycles:
    """Property: valid PRDs (built with forward deps only) have no cycles."""

    @given(prd=valid_prd(min_stories=1, max_stories=20))
    @settings(max_examples=200)
    def test_valid_prd_has_no_cycles(self, prd):
        """PRDs generated by our strategy never have cycles (deps only reference earlier stories)."""
        cycles = find_cycles(prd["userStories"])
        assert cycles == [], f"Expected no cycles, found: {cycles}"


class TestCyclesDetected:
    """Property: injected cycles are always found."""

    @given(prd=prd_with_cycle())
    @settings(max_examples=100)
    def test_cycle_is_detected(self, prd):
        cycles = find_cycles(prd["userStories"])
        assert len(cycles) > 0, "Cycle should be detected"

    def test_self_referencing_cycle(self):
        stories = [{"id": "US-001", "dependencies": ["US-001"]}]
        cycles = find_cycles(stories)
        assert "US-001" in cycles

    def test_mutual_cycle(self):
        stories = [
            {"id": "US-001", "dependencies": ["US-002"]},
            {"id": "US-002", "dependencies": ["US-001"]},
        ]
        cycles = find_cycles(stories)
        assert set(cycles) == {"US-001", "US-002"}

    def test_transitive_cycle(self):
        stories = [
            {"id": "US-001", "dependencies": ["US-003"]},
            {"id": "US-002", "dependencies": ["US-001"]},
            {"id": "US-003", "dependencies": ["US-002"]},
        ]
        cycles = find_cycles(stories)
        assert set(cycles) == {"US-001", "US-002", "US-003"}


class TestEdgeCases:
    """Edge cases for cycle detection."""

    def test_empty_stories(self):
        assert find_cycles([]) == []

    def test_no_dependencies(self):
        stories = [
            {"id": "US-001", "dependencies": []},
            {"id": "US-002", "dependencies": []},
        ]
        assert find_cycles(stories) == []

    def test_dangling_dep_ignored(self):
        """Dependencies to non-existent IDs should not cause false cycles."""
        stories = [
            {"id": "US-001", "dependencies": ["US-999"]},
        ]
        assert find_cycles(stories) == []
