import { useState, useEffect } from 'react';
import { CONFIG_FIELDS } from '../data/configSchema';
import type { ConfigValues } from './SettingsPanel';

// ── Helpers ────────────────────────────────────────────────────────────────────

function buildConfig(values: ConfigValues): string {
  // Fields that are NOT exported to spiral.config.sh (they become CLI flags instead)
  const CLI_ONLY = new Set(['MAX_SPIRAL_ITERS', 'SPIRAL_RALPH_ITERS', 'SPIRAL_GATE_MODE']);

  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# spiral.config.sh — generated by SPIRAL UI',
    `# Generated: ${new Date().toISOString()}`,
    '',
  ];

  let lastCategory = '';
  for (const field of CONFIG_FIELDS) {
    if (CLI_ONLY.has(field.key)) continue;
    if (field.category !== lastCategory) {
      lines.push(`# ── ${field.category} ${'─'.repeat(Math.max(0, 50 - field.category.length))}`);
      lastCategory = field.category;
    }
    const raw = values[field.key] ?? field.defaultValue;
    const val = String(raw);
    const isNoop = val === '' || val === '0' || val === 'false';
    const isDefault = val === String(field.defaultValue);
    const prefix = isNoop || isDefault ? '# ' : '';
    lines.push(`${prefix}export ${field.key}=${JSON.stringify(val)}`);
  }

  lines.push('');
  return lines.join('\n');
}

function buildLaunchCommand(values: ConfigValues): string {
  const SPIRAL_HOME = 'C:/Users/Jyue/.ai/Skills/spiral';

  const maxIters = Number(values['MAX_SPIRAL_ITERS'] ?? 20) || 20;
  const ralphIters = Number(values['SPIRAL_RALPH_ITERS'] ?? 120);
  const gateMode = String(values['SPIRAL_GATE_MODE'] ?? 'interactive');
  const workers = Number(values['SPIRAL_RALPH_WORKERS'] ?? 1);
  const model = String(values['SPIRAL_MODEL_ROUTING'] ?? 'auto');

  const parts: string[] = [
    `bash "${SPIRAL_HOME}/spiral.sh" ${maxIters}`,
  ];

  // gate
  if (gateMode === 'proceed') parts.push('--gate proceed');
  else if (gateMode === 'skip') parts.push('--gate skip');
  // 'interactive' = omit flag

  // ralph iters (only if non-default)
  if (ralphIters !== 120 && ralphIters > 0) parts.push(`--ralph-iters ${ralphIters}`);

  // workers
  if (workers > 1) parts.push(`--ralph-workers ${workers}`);

  // model (only if not auto)
  if (model !== 'auto' && model !== '') parts.push(`--model ${model}`);

  // capacity limit
  const capacity = Number(values['SPIRAL_CAPACITY_LIMIT'] ?? 50);
  if (capacity !== 50) parts.push(`--capacity-limit ${capacity}`);

  return parts.join(' \\\n  ');
}

// ── Component ──────────────────────────────────────────────────────────────────

export default function ConfigGenerator({ values }: { values: ConfigValues }) {
  const [copied, setCopied] = useState(false);
  const [saveState, setSaveState] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');
  const [savedPath, setSavedPath] = useState('');
  const [projectRoot, setProjectRoot] = useState<string | null>(null);

  const config = buildConfig(values);
  const launchCmd = buildLaunchCommand(values);

  // Fetch project root from the dev server API (only available when SPIRAL_PROJECT_ROOT is set)
  useEffect(() => {
    fetch('/api/project')
      .then(r => r.json())
      .then((d: { projectRoot?: string }) => { if (d.projectRoot) setProjectRoot(d.projectRoot); })
      .catch(() => {/* API not available in standalone mode */});
  }, []);

  const copy = async () => {
    await navigator.clipboard.writeText(config);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([config], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'spiral.config.sh';
    a.click();
    URL.revokeObjectURL(url);
  };

  const saveToProject = async () => {
    setSaveState('saving');
    try {
      const res = await fetch('/api/save-config', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: config }),
      });
      const data = await res.json() as { ok?: boolean; path?: string; error?: string };
      if (data.ok) {
        setSavedPath(data.path ?? '');
        setSaveState('saved');
      } else {
        setSaveState('error');
      }
    } catch {
      setSaveState('error');
    }
  };

  // Count active (non-default) settings
  const activeCount = CONFIG_FIELDS.filter(f => {
    const v = String(values[f.key] ?? f.defaultValue);
    return v !== String(f.defaultValue) && v !== '' && v !== '0' && v !== 'false';
  }).length;

  return (
    <div className="flex flex-col h-full gap-4">

      {/* ── Launch Command ──────────────────────────────────────────────────── */}
      <div className="rounded-xl border border-blue-200 bg-blue-50 overflow-hidden flex-shrink-0">
        <div className="px-4 py-2.5 bg-blue-600 flex items-center justify-between">
          <span className="text-white font-semibold text-sm">Launch Command</span>
          <span className="text-blue-200 text-xs">Run this in your project root after saving config</span>
        </div>
        <div className="px-4 py-3">
          <pre className="text-xs text-blue-900 font-mono whitespace-pre-wrap leading-relaxed">{launchCmd}</pre>
        </div>
      </div>

      {/* ── spiral.config.sh header bar ─────────────────────────────────────── */}
      <div className="flex items-center justify-between flex-wrap gap-2 flex-shrink-0">
        <div>
          <h3 className="font-semibold text-slate-800 text-sm">spiral.config.sh</h3>
          <p className="text-xs text-slate-500">
            {activeCount} active setting{activeCount !== 1 ? 's' : ''}
            {projectRoot && (
              <span className="ml-1 text-slate-400">→ <code className="text-[10px]">{projectRoot}</code></span>
            )}
          </p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button
            onClick={copy}
            className="px-3 py-1.5 text-xs font-medium rounded-lg border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 transition-colors"
          >
            {copied ? '✓ Copied!' : 'Copy'}
          </button>
          <button
            onClick={download}
            className="px-3 py-1.5 text-xs font-medium rounded-lg border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 transition-colors"
          >
            Download
          </button>
          {projectRoot && (
            <button
              onClick={saveToProject}
              disabled={saveState === 'saving'}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors ${
                saveState === 'saved'
                  ? 'bg-emerald-600 text-white'
                  : saveState === 'error'
                  ? 'bg-red-600 text-white'
                  : 'bg-blue-600 hover:bg-blue-700 text-white'
              }`}
            >
              {saveState === 'saving' ? 'Saving…'
                : saveState === 'saved' ? '✓ Saved to Project!'
                : saveState === 'error' ? '✗ Save Failed'
                : '💾 Save to Project'}
            </button>
          )}
        </div>
      </div>

      {/* Save success banner */}
      {saveState === 'saved' && savedPath && (
        <div className="flex-shrink-0 rounded-lg bg-emerald-50 border border-emerald-200 px-4 py-3 text-xs text-emerald-800">
          <div className="font-semibold mb-0.5">Config saved!</div>
          <code className="break-all opacity-80">{savedPath}</code>
          <div className="mt-2 text-emerald-700">
            Tell Claude <strong>"ready"</strong> or copy the launch command above and run it in your terminal.
          </div>
        </div>
      )}

      {/* Code preview */}
      <div className="flex-1 rounded-xl border border-slate-200 bg-slate-950 overflow-auto min-h-0">
        <pre className="p-4 text-xs text-slate-200 font-mono leading-relaxed whitespace-pre">{config}</pre>
      </div>

      {/* Usage hint */}
      <p className="text-[11px] text-slate-400 flex-shrink-0">
        {projectRoot
          ? <>Click <strong>Save to Project</strong> to write directly to <code className="bg-slate-100 px-1 rounded">{projectRoot}/spiral.config.sh</code>, then tell Claude <strong>"ready"</strong>.</>
          : <>Place <code className="bg-slate-100 px-1 rounded">spiral.config.sh</code> at the root of your project, then run the launch command above.</>
        }
      </p>
    </div>
  );
}
