import { useState } from 'react';
import { CONFIG_FIELDS } from '../data/configSchema';
import type { ConfigValues } from './SettingsPanel';

// ── Helpers ────────────────────────────────────────────────────────────────────

function buildConfig(values: ConfigValues): string {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# spiral.config.sh — generated by SPIRAL UI',
    `# Generated: ${new Date().toISOString()}`,
    '',
  ];

  let lastCategory = '';

  for (const field of CONFIG_FIELDS) {
    if (field.category !== lastCategory) {
      lines.push(`# ── ${field.category} ${'─'.repeat(Math.max(0, 50 - field.category.length))}`);
      lastCategory = field.category;
    }

    const raw = values[field.key] ?? field.defaultValue;
    const val = String(raw);
    const isDefault = val === String(field.defaultValue);

    // Comment-out lines that are still at default (zero / empty / disabled)
    const isNoop = val === '' || val === '0' || val === 'false';
    const prefix = isNoop || isDefault ? '# ' : '';

    lines.push(`${prefix}export ${field.key}=${JSON.stringify(val)}`);
  }

  lines.push('');
  return lines.join('\n');
}

// ── Component ──────────────────────────────────────────────────────────────────

export default function ConfigGenerator({ values }: { values: ConfigValues }) {
  const [copied, setCopied] = useState(false);
  const config = buildConfig(values);

  const copy = async () => {
    await navigator.clipboard.writeText(config);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([config], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'spiral.config.sh';
    a.click();
    URL.revokeObjectURL(url);
  };

  // Count active (non-default) settings
  const activeCount = CONFIG_FIELDS.filter(f => {
    const v = String(values[f.key] ?? f.defaultValue);
    return v !== String(f.defaultValue) && v !== '' && v !== '0' && v !== 'false';
  }).length;

  return (
    <div className="flex flex-col h-full gap-3">
      {/* Header bar */}
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div>
          <h3 className="font-semibold text-slate-800 text-sm">spiral.config.sh</h3>
          <p className="text-xs text-slate-500">
            {activeCount} active setting{activeCount !== 1 ? 's' : ''} (non-default lines are uncommented)
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={copy}
            className="px-3 py-1.5 text-xs font-medium rounded-lg border border-slate-300 bg-white hover:bg-slate-50 text-slate-700 transition-colors"
          >
            {copied ? '✓ Copied!' : 'Copy'}
          </button>
          <button
            onClick={download}
            className="px-3 py-1.5 text-xs font-medium rounded-lg bg-blue-600 hover:bg-blue-700 text-white transition-colors"
          >
            Download
          </button>
        </div>
      </div>

      {/* Code preview */}
      <div className="flex-1 rounded-xl border border-slate-200 bg-slate-950 overflow-auto">
        <pre className="p-4 text-xs text-slate-200 font-mono leading-relaxed whitespace-pre">{config}</pre>
      </div>

      {/* Usage hint */}
      <p className="text-[11px] text-slate-400">
        Place <code className="bg-slate-100 px-1 rounded">spiral.config.sh</code> at the root of your project, then run{' '}
        <code className="bg-slate-100 px-1 rounded">source spiral.config.sh && spiral.sh</code>
      </p>
    </div>
  );
}
