#!/usr/bin/env python3
"""api_docs_generator.py — Generate HTML API documentation from lib/ modules using pdoc.

CLI tool for creating navigable HTML API reference documentation from Python
modules. Generates an index.html with cross-module links.

Usage:
    uv run python lib/api_docs_generator.py lib/ --output docs/api/
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import pdoc
except ImportError:
    print("Error: pdoc is not installed. Install with: uv pip install pdoc", file=sys.stderr)
    sys.exit(1)


def collect_modules(source_dir: Path) -> list[str]:
    """Collect all Python module names from source directory.

    Args:
        source_dir: Directory containing Python modules

    Returns:
        List of module names (without .py extension)
    """
    modules: list[str] = []
    if not source_dir.is_dir():
        return modules

    for py_file in sorted(source_dir.glob("*.py")):
        # Skip test files and private modules
        if py_file.name.startswith("test_") or py_file.name.startswith("_"):
            continue
        if py_file.name == "__init__.py":
            continue
        modules.append(py_file.stem)

    return modules


def create_index_html(modules: list[str], output_dir: Path) -> None:
    """Create index.html with links to all module documentation.

    Args:
        modules: List of module names
        output_dir: Output directory for index.html
    """
    html_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SPIRAL API Documentation</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 40px 20px;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            padding: 40px;
        }
        h1 {
            color: #667eea;
            margin-bottom: 10px;
            font-size: 2.5em;
        }
        .subtitle {
            color: #666;
            margin-bottom: 30px;
            font-size: 1.1em;
        }
        .modules-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-top: 30px;
        }
        .module-card {
            background: #f8f9fa;
            border: 1px solid #ddd;
            border-radius: 6px;
            padding: 20px;
            transition: all 0.3s ease;
            text-decoration: none;
            color: inherit;
        }
        .module-card:hover {
            border-color: #667eea;
            box-shadow: 0 4px 12px rgba(102, 126, 234, 0.15);
            transform: translateY(-2px);
        }
        .module-name {
            font-weight: 600;
            color: #667eea;
            font-size: 1.1em;
            margin-bottom: 5px;
        }
        .module-link {
            color: #667eea;
            text-decoration: none;
        }
        .module-link:hover {
            text-decoration: underline;
        }
        .generated-info {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #999;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>SPIRAL API Documentation</h1>
        <p class="subtitle">Python module reference for SPIRAL orchestration framework</p>

        <div class="modules-grid">
"""

    for module in modules:
        html_content += f"""            <div class="module-card">
                <div class="module-name">{module}</div>
                <a href="{module}.html" class="module-link">View Documentation →</a>
            </div>
"""

    html_content += """        </div>

        <div class="generated-info">
            <p>Generated by pdoc. Each module's full API documentation is available via the links above.</p>
        </div>
    </div>
</body>
</html>
"""

    index_file = output_dir / "index.html"
    with open(index_file, "w", encoding="utf-8") as f:
        f.write(html_content)


def generate_api_docs(source_dir: str | Path, output_dir: str | Path) -> None:
    """Generate HTML API documentation from Python modules using pdoc.

    Args:
        source_dir: Path to source directory containing Python modules
        output_dir: Path to output directory for generated HTML docs

    Raises:
        RuntimeError: If pdoc generation fails
        FileNotFoundError: If source directory does not exist
    """
    source_path = Path(source_dir)
    output_path = Path(output_dir)

    if not source_path.is_dir():
        raise FileNotFoundError(f"Source directory not found: {source_path}")

    # Create output directory
    output_path.mkdir(parents=True, exist_ok=True)

    # Collect module names
    modules = collect_modules(source_path)
    if not modules:
        raise RuntimeError(f"No Python modules found in {source_path}")

    print(f"Generating API documentation for {len(modules)} modules...")

    # Generate HTML for each module using pdoc
    try:
        # Add source directory to sys.path temporarily
        import sys as sys_module

        sys_module.path.insert(0, str(source_path.parent))

        for module_name in modules:
            try:
                # Import the module to generate docs
                mod = __import__(module_name)

                # Use pdoc to render HTML
                html: str = pdoc.render(mod)  # type: ignore[operator]

                # Write to file
                module_file = output_path / f"{module_name}.html"
                with open(module_file, "w", encoding="utf-8") as f:
                    f.write(html)

                print(f"  ✓ {module_name}")
            except (ImportError, Exception) as e:
                print(f"  ✗ {module_name}: {e}", file=sys.stderr)

        # Create index.html with cross-module links
        create_index_html(modules, output_path)
        print("  ✓ index.html")

        print(f"\nAPI documentation generated in: {output_path.resolve()}")

    except Exception as e:
        raise RuntimeError(f"Failed to generate API documentation: {e}") from e


def main() -> None:
    """CLI entry point for API documentation generator."""
    parser = argparse.ArgumentParser(description="Generate HTML API documentation from Python modules using pdoc")
    parser.add_argument("source_dir", help="Path to source directory containing Python modules")
    parser.add_argument("--output", default="docs/api", help="Output directory for generated HTML (default: docs/api)")

    args = parser.parse_args()

    try:
        generate_api_docs(args.source_dir, args.output)
        print("\n✅ API documentation generation complete")
    except (FileNotFoundError, RuntimeError) as e:
        print(f"\n❌ Error: {e}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("\n⚠ Generation cancelled by user", file=sys.stderr)
        sys.exit(130)


if __name__ == "__main__":
    main()
