#!/usr/bin/env python3
"""Generate html/data.js from prd.json for SPIRAL dashboard.

Exports window.SPIRAL_DATA = {
  storiesTotal: number,
  storiesPassed: number,
  lastUpdated: ISO timestamp
}
"""

import json
from datetime import datetime, timezone


def read_prd_json(prd_path: str) -> dict:
    """Read and parse prd.json."""
    with open(prd_path, encoding="utf-8") as f:
        return json.load(f)


def count_stories(data: dict) -> tuple[int, int]:
    """Count total stories and stories with passes=true.

    Returns:
        (total_stories, stories_passed)
    """
    stories = data.get("userStories", [])
    total = len(stories)
    passed = sum(1 for s in stories if s.get("passes") is True)
    return total, passed


def generate_data_js(output_path: str, prd_path: str) -> None:
    """Generate html/data.js from prd.json."""
    prd_data = read_prd_json(prd_path)
    total, passed = count_stories(prd_data)

    # ISO timestamp at generation time
    now = datetime.now(timezone.utc).isoformat()

    # Generate JavaScript with proper escaping
    js_content = f"""// Generated by lib/gen_html_data.py
// Do not edit manually

window.SPIRAL_DATA = {{
  storiesTotal: {total},
  storiesPassed: {passed},
  lastUpdated: "{now}"
}};
"""

    # Write output
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Generated {output_path}: {total} total, {passed} passed")


def main() -> None:
    """Main entry point."""
    # Paths relative to repo root
    prd_path = "prd.json"
    output_path = "html/data.js"

    generate_data_js(output_path, prd_path)


if __name__ == "__main__":
    main()
