"""
lib/commands/deploy_docs.py — Deploy CHANGELOG and pdoc outputs to GitHub Pages (US-732).

Implements ``spiral deploy-docs --branch gh-pages``:
- Creates .spiral/changelog-output/ with CHANGELOG.md and pdoc/ subdirectory
- Uses git worktree to manage gh-pages branch (avoids merge conflicts)
- Copies outputs, commits, and pushes without force push

Functions:
    prepare_changelog_output(spiral_home, prd_path) -> Path
        Copy CHANGELOG.md and .spiral/docs/api to .spiral/changelog-output/

    deploy_to_gh_pages(spiral_home, branch, worktree_dir, dry_run) -> None
        Commit and push changelog-output to the given branch via git worktree
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path


def _run(cmd: list[str], cwd: Path | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    """Run a subprocess command, streaming output."""
    result = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        capture_output=True,
        text=True,
    )
    if check and result.returncode != 0:
        raise RuntimeError(f"Command failed: {' '.join(cmd)}\nstdout: {result.stdout}\nstderr: {result.stderr}")
    return result


def prepare_changelog_output(
    spiral_home: Path,
    prd_path: Path,
) -> Path:
    """Stage CHANGELOG.md and pdoc outputs into .spiral/changelog-output/.

    Creates the directory structure expected by deploy_to_gh_pages:
        .spiral/changelog-output/
            CHANGELOG.md        (copied from <spiral_home>/CHANGELOG.md)
            pdoc/               (copied from <spiral_home>/.spiral/docs/api/)
                index.html
                ...

    If CHANGELOG.md does not exist, generates a minimal one from prd.json.
    If pdoc dir does not exist, creates a minimal index.html placeholder.

    Returns:
        Path to .spiral/changelog-output/
    """
    output_dir = spiral_home / ".spiral" / "changelog-output"
    output_dir.mkdir(parents=True, exist_ok=True)

    # --- CHANGELOG.md ---
    changelog_src = spiral_home / "CHANGELOG.md"
    if not changelog_src.exists():
        # Generate minimal changelog from prd.json passed stories
        changelog_src = _generate_minimal_changelog(spiral_home, prd_path)

    shutil.copy2(str(changelog_src), str(output_dir / "CHANGELOG.md"))

    # --- pdoc/ ---
    pdoc_src = spiral_home / ".spiral" / "docs" / "api"
    pdoc_dest = output_dir / "pdoc"
    pdoc_dest.mkdir(parents=True, exist_ok=True)

    if pdoc_src.exists() and any(pdoc_src.iterdir()):
        # Copy all pdoc outputs
        if pdoc_dest.exists():
            shutil.rmtree(str(pdoc_dest))
        shutil.copytree(str(pdoc_src), str(pdoc_dest))
    else:
        # Create minimal placeholder index.html
        (pdoc_dest / "index.html").write_text(
            "<!DOCTYPE html>\n<html><head><title>SPIRAL API Docs</title></head>\n"
            "<body><h1>SPIRAL API Documentation</h1>"
            "<p>Generated by spiral deploy-docs (US-732)</p></body></html>\n",
            encoding="utf-8",
        )

    print(f"[deploy-docs] Staged outputs to {output_dir}")
    return output_dir


def _generate_minimal_changelog(spiral_home: Path, prd_path: Path) -> Path:
    """Create a minimal CHANGELOG.md from prd.json completed stories.

    Returns:
        Path to the generated CHANGELOG.md in .spiral/
    """
    changelog_path = spiral_home / ".spiral" / "CHANGELOG.md"

    stories: list[dict[str, object]] = []
    if prd_path.exists():
        with open(prd_path, encoding="utf-8") as f:
            data = json.load(f)
        stories = [
            s for s in data.get("userStories", []) if s.get("passes") is True and not s.get("_decomposed", False)
        ]

    lines = ["# Changelog", "", "## Unreleased", ""]
    for s in stories:
        title = s.get("title", "Untitled")
        story_id = s.get("id", "")
        lines.append(f"- **{story_id}** {title}")
    lines.append("")

    changelog_path.write_text("\n".join(lines), encoding="utf-8")
    return changelog_path


def deploy_to_gh_pages(
    spiral_home: Path,
    branch: str = "gh-pages",
    worktree_dir: Path | None = None,
    dry_run: bool = False,
) -> None:
    """Deploy .spiral/changelog-output/ to the target branch via git worktree.

    Creates an isolated git worktree for the target branch, copies the staged
    outputs into it, commits, and pushes — WITHOUT force push.

    Args:
        spiral_home:  Project root (must be a git repo)
        branch:       Target branch name (default: gh-pages)
        worktree_dir: Override for worktree location (default: .spiral/workers/gh-pages-deploy)
        dry_run:      If True, stage and commit but skip the push

    Raises:
        RuntimeError: If source directory is missing or git operations fail
    """
    output_dir = spiral_home / ".spiral" / "changelog-output"
    if not output_dir.exists():
        raise RuntimeError(
            f"[deploy-docs] Source directory not found: {output_dir}\n"
            "Run 'spiral deploy-docs' after Phase G to prepare outputs first."
        )

    wt_dir = worktree_dir or (spiral_home / ".spiral" / "workers" / "gh-pages-deploy")
    wt_dir.parent.mkdir(parents=True, exist_ok=True)

    # Remove stale worktree if present
    if wt_dir.exists():
        _run(["git", "worktree", "remove", "--force", str(wt_dir)], cwd=spiral_home, check=False)
        shutil.rmtree(str(wt_dir), ignore_errors=True)

    # Check if branch exists remotely or locally
    remote_ref = _run(
        ["git", "ls-remote", "--heads", "origin", branch],
        cwd=spiral_home,
        check=False,
    )
    branch_exists_remote = bool(remote_ref.stdout.strip())

    local_branch = _run(
        ["git", "branch", "--list", branch],
        cwd=spiral_home,
        check=False,
    )
    branch_exists_local = bool(local_branch.stdout.strip())

    if branch_exists_local or branch_exists_remote:
        # Check out existing branch into worktree
        _run(
            ["git", "worktree", "add", str(wt_dir), branch],
            cwd=spiral_home,
        )
    else:
        # Create orphan branch in worktree
        _run(
            ["git", "worktree", "add", "--orphan", "-b", branch, str(wt_dir)],
            cwd=spiral_home,
        )

    try:
        wt_path = Path(wt_dir)

        # Clear existing content (keep .git)
        for item in wt_path.iterdir():
            if item.name == ".git":
                continue
            if item.is_dir():
                shutil.rmtree(str(item))
            else:
                item.unlink()

        # Copy staged outputs into worktree
        changelog_src = output_dir / "CHANGELOG.md"
        if changelog_src.exists():
            shutil.copy2(str(changelog_src), str(wt_path / "CHANGELOG.md"))

        pdoc_src = output_dir / "pdoc"
        if pdoc_src.exists():
            docs_dest = wt_path / "docs"
            if docs_dest.exists():
                shutil.rmtree(str(docs_dest))
            shutil.copytree(str(pdoc_src), str(docs_dest))

        # Add .nojekyll to avoid GitHub Pages Jekyll processing
        (wt_path / ".nojekyll").write_text("", encoding="utf-8")

        # Stage all files
        _run(["git", "add", "-A"], cwd=wt_path)

        # Check if there are changes to commit
        status = _run(["git", "status", "--porcelain"], cwd=wt_path, check=False)
        if not status.stdout.strip():
            print(f"[deploy-docs] No changes to commit on branch '{branch}'")
            return

        # Commit
        _run(
            ["git", "commit", "-m", f"docs: deploy CHANGELOG and API docs to {branch} (US-732)"],
            cwd=wt_path,
        )
        print(f"[deploy-docs] Committed docs to branch '{branch}'")

        if dry_run:
            print(f"[deploy-docs] --dry-run: skipping push to '{branch}'")
            return

        # Push (never force push)
        _run(["git", "push", "origin", branch], cwd=wt_path)
        print(f"[deploy-docs] Pushed docs to origin/{branch}")

    finally:
        # Always clean up the worktree
        _run(
            ["git", "worktree", "remove", "--force", str(wt_dir)],
            cwd=spiral_home,
            check=False,
        )
        shutil.rmtree(str(wt_dir), ignore_errors=True)
        print(f"[deploy-docs] Cleaned up worktree at {wt_dir}")
